version: "3"

services:
  hello1:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_FILE: index.js
    image: hello:v0.2
    volumes:
      - hello1-volume:/tmp
    environment:
      ENVIRONMENT_VARIABLE: value

  hello2:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SOURCE_FILE: index2.js
    image: hello:v0.2
    volumes:
      - hello2-volume:/tmp
    environment:
      ENVIRONMENT_VARIABLE: value

volumes:
  hello1-volume:
  hello2-volume:
